# Liga o console do H2
spring.h2.console.enabled=true

# Define o caminho do console
spring.h2.console.path=/h2-console

# Configura o banco em memoria para evitar URLs aleatorias
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto para o Hibernate entender o H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Faz o Hibernate criar as tabelas
spring.jpa.hibernate.ddl-auto=create

# Faz o Spring rodar o import.sql ou data.sql DEPOIS que o Hibernate criou as tabelas
spring.jpa.defer-datasource-initialization=true

# Mostrar o SQL no console (ajuda a depurar a procedure)
spring.jpa.show-sql=true